In [126]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [127]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [128]:
X = df.drop('species', axis = 1)
y = df['species']

In [129]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

KNN

In [130]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors = 5)

In [131]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [132]:
model_knn.score(X_test,y_test)

1.0

SVM

In [133]:
from sklearn.svm import SVC

model_svc = SVC(C = 30, kernel = 'rbf', gamma= 'auto')

In [134]:
model_svc.fit(X_train, y_train)

SVC(C=30, gamma='auto')

In [135]:
model_svc.score(X_test,y_test)

1.0

**Grid search cv** ---> here no need of train test split

for SVM

In [136]:
from sklearn.model_selection import GridSearchCV

In [137]:
classifier_svc = GridSearchCV((model_svc),{
    'C': [1,10,20,30],
    'kernel': ['rbf', 'linear'],
}, cv = 5 , return_train_score= False)

In [138]:
classifier_svc.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [139]:
results = pd.DataFrame(classifier_svc.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003045,0.000379,0.002144,0.000414,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003496,0.002118,0.002028,0.000256,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002544,0.000135,0.001968,0.000221,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002367,0.000114,0.001779,0.000116,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002348,0.000051,0.001741,0.000037,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002243,0.000050,0.001691,0.000023,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002316,0.000019,0.001729,0.000045,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002273,0.000047,0.001827,0.000198,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [140]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

for Knn

In [141]:
classifier_knn = GridSearchCV((model_knn),{
    'n_neighbors': [3,5,7,9,11,13],
    'weights': ['uniform','distance'],
    'metric': ['euclidean', 'manhattan', 'chebyshev', 'hamming'],
},cv = 5, return_train_score = False)

In [142]:
classifier_knn.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan', 'chebyshev',
                                    'hamming'],
                         'n_neighbors': [3, 5, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']})

In [143]:
result_knn = pd.DataFrame(classifier_knn.cv_results_)
result_knn.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_metric', 'param_n_neighbors', 'param_weights', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'split3_test_score', 'split4_test_score', 'mean_test_score',
       'std_test_score', 'rank_test_score'],
      dtype='object')

In [144]:
result_knn[['param_metric', 'param_n_neighbors', 'param_weights','mean_test_score']]

   param_metric  param_n_neighbors param_weights  mean_test_score
0     euclidean                  3       uniform         0.966667
1     euclidean                  3      distance         0.966667
2     euclidean                  5       uniform         0.973333
3     euclidean                  5      distance         0.966667
4     euclidean                  7       uniform         0.980000
5     euclidean                  7      distance         0.980000
6     euclidean                  9       uniform         0.973333
7     euclidean                  9      distance         0.973333
8     euclidean                 11       uniform         0.980000
9     euclidean                 11      distance         0.986667
10    euclidean                 13       uniform         0.973333
11    euclidean                 13      distance         0.980000
12    manhattan                  3       uniform         0.960000
13    manhattan                  3      distance         0.960000
14    manhattan                  5       uniform         0.960000
15    manhattan                  5      distance         0.960000
16    manhattan                  7       uniform         0.973333
17    manhattan                  7      distance         0.960000
18    manhattan                  9       uniform         0.973333
19    manhattan                  9      distance         0.960000
20    manhattan                 11       uniform         0.980000
21    manhattan                 11      distance         0.966667
22    manhattan                 13       uniform         0.973333
23    manhattan                 13      distance         0.966667
24    chebyshev                  3       uniform         0.960000
25    chebyshev                  3      distance         0.960000
26    chebyshev                  5       uniform         0.986667
27    chebyshev                  5      distance         0.986667
28    chebyshev                  7       uniform         0.986667
29    chebyshev                  7      distance         0.986667
30    chebyshev                  9       uniform         0.980000
31    chebyshev                  9      distance         0.980000
32    chebyshev                 11       uniform         0.966667
33    chebyshev                 11      distance         0.980000
34    chebyshev                 13       uniform         0.953333
35    chebyshev                 13      distance         0.980000
36      hamming                  3       uniform         0.686667
37      hamming                  3      distance         0.720000
38      hamming                  5       uniform         0.666667
39      hamming                  5      distance         0.713333
40      hamming                  7       uniform         0.673333
41      hamming                  7      distance         0.733333
42      hamming                  9       uniform         0.693333
43      hamming                  9      distance         0.760000
44      hamming                 11       uniform         0.706667
45      hamming                 11      distance         0.760000
46      hamming                 13       uniform         0.740000
47      hamming                 13      distance         0.753333